[workspace]
resolver = "2"
members = ["crates/tremista-dock", "crates/tremista-dock-core"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/tremista/tremista-desktop"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
